version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/base:2020.01

    steps:
      #- checkout

      - add_ssh_keys:
          fingerprints:
            - 'ad:e1:02:66:71:97:15:90:82:bf:18:b1:a0:bb:7f:b0'
      - run:
          name: Copy over ssh
          command:
            scp -o StrictHostKeyChecking=no -r -p ./* $SSH_USER@$SSH_HOST:/var/www/www.carto-api.jeromehenry.fr/

      - run:
          name: connect via ssh
          command:
            ssh StrictHostKeyChecking=no $SSH_USER@$SSH_HOST:/var/www/www.carto-api.jeromehenry.fr/

      - run:
          name: composer install deps
          command:
            composer install -n --prefer-dist
