version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - 'e0:63:1e:da:e9:07:87:f1:34:41:61:44:98:fb:68:5c'
      - run:
          name: Copy over ssh
          command:
            scp -o StrictHostKeyChecking=no -r -p ./* $SSH_USER@$SSH_HOST:/var/www/www.carto-api.jeromehenry.fr/

      -run:
          name: connect via ssh
          command:
            ssh StrictHostKeyChecking=no $SSH_USER@$SSH_HOST:/var/www/www.carto-api.jeromehenry.fr/

      -run:
          name: composer install deps
          command:
            composer install -n --prefer-dist
